# Generated by Django 4.2.24 on 2025-09-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
